name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: paket-apk
          path: ${{ steps.buildozer.outputs.filename }}
          
